### ISSUE TITLE
[Feature Request] Hot reload for header format?

### ISSUE THREAD

**Issue by atticus-lv** [daenvil/MarkdownLabel#14]
I noticed that only restart the game will update the title size( And the size will not change in the editor until you modifier the bbcode)

**Comment by daenvil** [comment]
I wasn't able to replicate the issue in-game (changing the header format in the editor did update it inside the game in real time)

The issue within the editor was caused due to the header format scripts not having the ``@tool`` annotation. Fixed now in e5caf7d3f7558476963fd759fd3dd5e667a0b3d0 :)
