### ISSUE TITLE
Add reference links support 

### ISSUE THREAD

**Issue by daenvil** [daenvil/MarkdownLabel#3]
I think it could be possible using [RichTextLabel.scroll_to_line()](https://docs.godotengine.org/en/stable/classes/class_richtextlabel.html#class-richtextlabel-method-scroll-to-line)

**Comment by snipercup** [comment]
Hey I was about to use [dialogic's markdown parser ](https://github.com/coppolaemilio/dialogic/blob/dialogic-1/addons/dialogic/Documentation/Nodes/DocsMarkdownParser.gd) but I found your addon and it's exactly what I need! I just want to say that dialogic implemented the markdown 'sections' that can be linked to. I haven't seen it in action but you might find another solution there.
